application/application/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('goods.urls')),
                  path('', include('client.urls')),
                  path('', include('client_goods_relation.urls')),
                  path('auth/', include('djoser.urls')),
                  path('auth/', include('djoser.urls.jwt')),
                  path('api/auth/social/', include('djoser.social.urls')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/goods/urls.py
from rest_framework.routers import SimpleRouter
from django.urls import path

from goods.views import GoodsModelView, CategoryModelView, SizeModelView, GoodsCreateModelView

urlpatterns = [
    path('api/goods/create', GoodsCreateModelView.as_view()),
]

router = SimpleRouter()
router.register('api/goods', GoodsModelView)
router.register('api/category', CategoryModelView)
router.register('api/size', SizeModelView)
urlpatterns += router.urls

application/client_goods_relation/models.py
from django.conf import settings
from django.db import models

from goods.models import Goods


class Like(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)
    like = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.owner.username}: Book {self.goods.name}'


class Comment(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                              blank=True, related_name='owner_comment')
    text = models.TextField()
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, related_name='comment')


class InFavorites(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    favorite = models.BooleanField(default=False)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)


class Basket(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=1)

application/goods/models.py
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.text import slugify


class GoodsSize(models.Model):
    size_name = models.CharField(max_length=50)
    size_value = models.DecimalField(max_digits=6, decimal_places=2, null=True, default=None, blank=True)

    def __str__(self):
        return f'{self.size_name} {self.size_value}'


class GoodsCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse(f'{self.name}')


class Goods(models.Model):
    def file_name(instance, filename):
        return '/'.join(['images', str(instance.name), filename])

    name = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True, verbose_name='URL')
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0)])
    image = models.ImageField(upload_to=file_name)
    size = models.ManyToManyField(GoodsSize, related_name='size_goods')
    discount = models.PositiveIntegerField(default=0, validators=[MaxValueValidator(100)])
    time_create = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='category_goods')
    is_published = models.BooleanField(default=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True)
    company_name = models.CharField(max_length=255)

    class Meta:
        ordering = ['-time_create']

    def __str__(self):
        return f'{self.name} :{self.price}'

    def get_absolute_url(self):
        return reverse('goods_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)


class GoodsImages(models.Model):
    title = models.CharField(max_length=100, blank=True)
    image = models.ImageField(upload_to=f'photo/')
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, related_name='goods_images')

    def __str__(self):
        return self.title

application/goods/views.py
from django.db.models import Count, Case, F, When, Prefetch
from djoser.conf import User
from rest_framework import status
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import ReadOnlyModelViewSet

from goods.models import Goods, GoodsCategory, GoodsSize
from goods.permissions import IsOwnerOrStaffOrReadOnly
from goods.serializers import GoodsListSerializer, GoodsCreateSerializer, CategorySerializer, SizeSerializer, \
    GoodsDitailSerializer
from goods.viewsets import NotCreateViewSet


class GoodsModelView(NotCreateViewSet):
    queryset = Goods.objects.all().annotate(likes=Count(Case(When(like__like=True, then=1))),
                                            price_with_discount=(F('price') -
                                                                 F('price') *
                                                                 F('discount') / 100),
                                            ).order_by('time_create').select_related('category').prefetch_related(
        Prefetch('owner', queryset=User.objects.all().select_related('user').only('username')))
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['name', 'owner_name', 'category', 'company_name']
    ordering_fields = ['price_with_discount', 'name', 'likes', 'time_create']
    permission_classes = [IsOwnerOrStaffOrReadOnly]

    def get_serializer_class(self):
        if self.action == 'list':
            return GoodsListSerializer
        else:
            return GoodsDitailSerializer


class GoodsCreateModelView(CreateAPIView):
    queryset = Goods.objects.all()
    serializer_class = GoodsCreateSerializer
    permission_classes = [IsAuthenticated]

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        serializer.validated_data['owner'] = self.request.user
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)


class CategoryModelView(ReadOnlyModelViewSet):
    queryset = GoodsCategory.objects.all().order_by('name').prefetch_related('category_goods')
    serializer_class = CategorySerializer


class SizeModelView(ReadOnlyModelViewSet):
    queryset = GoodsSize.objects.all().order_by('size_name').prefetch_related('size_goods__category')
    serializer_class = SizeSerializer

application/goods/templates/goods/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'goods/css/stylesproducts.css' %}">
    <link rel="stylesheet" href="{%static 'goods/css/stylesnovbrav.css' %}">
<!--For custom css-->
    {% block css %} {% endblock %}
</head>
<body>
    <div class="Navbar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <div class="icon-image">
                    <nav class="navbar navbar-light bg-light">
                        <div class="container-fluid">
                          <a class="navbar-brand" href="#">
                            <img src="{% static 'goods/images/icon.png' %}" alt="" width="50" height="50" class="d-inline-block align-text-top">
                                Bootstrap
                          </a>
                        </div>
                      </nav>
                </div>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="#">Sale</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Shoes</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Clothe</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Other</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Brends
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="#">Nike</a></li>
                      <li><a class="dropdown-item" href="#">Adidas</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Lui</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </div>
{% block content %} {% endblock %}
    <div class="homeimages">
        <div class="helpmenu">
            <img src="{% static 'goods/images/help.jpg' %}" class="img-fluid" alt="...">
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

application/goods/templates/goods/basehtml.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'goods/css/stylesproducts.css' %}">
    <link rel="stylesheet" href="{%static 'goods/css/stylesnovbrav.css' %}">
</head>
<body>
    <div class="Navbar">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <div class="icon-image">
                    <nav class="navbar navbar-light bg-light">
                        <div class="container-fluid">
                          <a class="navbar-brand" href="#">
                            <img src="source/images/icon.png" alt="" width="50" height="50" class="d-inline-block align-text-top">
                                Bootstrap
                          </a>
                        </div>
                      </nav>
                </div>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link" href="#">Sale</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Shoes</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Clothe</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">Other</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Brends
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                      <li><a class="dropdown-item" href="#">Nike</a></li>
                      <li><a class="dropdown-item" href="#">Adidas</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">Lui</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </div>
    <div class="homeimages">
        <div class="helpmenu">
            <img src="{% static 'goods/images/help.jpg' %}" class="img-fluid" alt="...">
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

application/goods/templates/goods/homepage.html
{% extends 'goods/base.html' %}
{% load rest_framework %}
{% load static %}

{% block content %}
    <div class="homeimages">
        <div class="homenewimage">
            <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
                  <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                  <div class="carousel-item active">
                    <img src="{% static 'goods/images/imageforshop.png' %}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'goods/images/imageforshop.png' %}" class="d-block w-100" alt="...">
                  </div>
                  <div class="carousel-item">
                    <img src="{% static 'goods/images/imageforshop.png' %}" class="d-block w-100" alt="...">
                  </div>
                </div>
                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
        </div>
    </div>
    <div class="category">
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Shoes</a>
            </div>
          </nav>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Shoes</h5>
                  <p class="card-text">250$</p>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">50$</p>
                </div>
              </div>
            </div>
            <div class="col">
                <div class="card h-100">
                  <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">50$</p>
                  </div>
                </div>
              </div>
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">500$</p>
                </div>
              </div>
            </div>
          </div>
    </div>
    <div class="category">
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Shoes</a>
            </div>
          </nav>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Shoes</h5>
                  <p class="card-text">250$</p>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">50$</p>
                </div>
              </div>
            </div>
            <div class="col">
                <div class="card h-100">
                  <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">50$</p>
                  </div>
                </div>
              </div>
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">500$</p>
                </div>
              </div>
            </div>
          </div>
    </div>
    <div class="category">
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Shoes</a>
            </div>
          </nav>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Shoes</h5>
                  <p class="card-text">250$</p>
                </div>
              </div>
            </div>
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">50$</p>
                </div>
              </div>
            </div>
            <div class="col">
                <div class="card h-100">
                  <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                  <div class="card-body">
                    <h5 class="card-title">Card title</h5>
                    <p class="card-text">50$</p>
                  </div>
                </div>
              </div>
            <div class="col">
              <div class="card h-100">
                <img src="source/images/Untitled1.jpg" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">Card title</h5>
                  <p class="card-text">500$</p>
                </div>
              </div>
            </div>
          </div>
    </div>
{% endblock %}

application/goods/templates/goods/productpage.html
{% extends 'goods/base.html' %}
{% load rest_framework %}
{% load static %}


{% block content %}
    <div class="MainInfo">
        <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
          <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="10000">
              <img src="{{ object.images.url }}" class="d-block w-50" alt="...">
            </div>
              {% for image in object.goodsimages_set.all %}
            <div class="carousel-item" data-bs-interval="2000">
              <img src="{{ image.image.url }}" class="d-block w-50" alt="...">
            </div>
              {% endfor %}
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
        <button type="button" class="btn btn-outline-secondary">Добавить в корзину</button>
        <button type="button" class="btn btn-outline-secondary">Купить</button>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Name -{{object.name}} </li>
            <li class="list-group-item">Author - {{object.owner}}</li>
            <li class="list-group-item">Price -{{object.price}}$</li>
            <li class="list-group-item">Description - {{object.description}}</li>
            <li class="list-group-item">Company - {{object.company_name}}</li>
            <li class="list-group-item">Published - {{object.is_published}}</li>
            <li class="list-group-item">Size :</li>
            <ul class="list-group">
                {% for size in object.size.all %}
                <li class="list-group-item">
                  <input class="form-check-input me-1" type="checkbox" value="" aria-label="...">
                  {{size}}
                </li>
                {% endfor %}
              </ul>
          </ul>
                            <form action="{% url 'add_comment' goods.id %}" method="post" class="mt-4">
                        {% csrf_token %}
                        <div class="form-group editContent">
                            <label for="contactcomment" class="editContent">
                                Ваш комментарий *
                            </label>
                            <textarea class="form-control border" rows="5" name="text"
                                      id="contactcomment" required=""></textarea>
                        </div>
                        <div class="d-sm-flex">
                            <div class="col-sm-6 form-group ml-sm-3 editContent">
                                <label for="contactemail" class="editContent">
                                    Email *
                                </label>
                                <input type="email" class="form-control border" name="email"
                                       id="contactemail" required="">
                            </div>
                        </div>
                        <button type="submit"
                                class="mt-3 btn btn-success btn-block py-3">
                            Отправить
                        </button>
                    </form>
         {% for comment in goods.comment_set.all %}
            <div class="media py-5">
                <div class="media-body mt-4">
                    <h5 class="mt-0 editContent">
                        {{ comment.email }}
                    </h5>
                    <p class="mt-2 editContent">
                        {{ comment.text }}
                    </p>
                    </div>
                </div>
        {% endfor %}

    </div>
{% endblock %}

application/goods/templates/goods/products.html
{% extends 'goods/base.html' %}
{% load rest_framework %}
{% load static %}


{% block content %}
    <div class="button-sort">
        <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
            <button type="button" class="btn btn-light">sort by newest</button>
            <button type="button" class="btn btn-light">sort by price</button>
          </div>
    </div>
    <div class="category">
        <nav class="navbar navbar-light bg-light">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Shoes</a>
            </div>
          </nav>
          <div class="row row-cols-1 row-cols-md-3 g-4">
            {% for object in object_list %}
            <a href="{{ object.get_absolute_url }}">
                <div class="col">
              <div class="card h-100">
                <img src="{{ object.images.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                  <h5 class="card-title">{{object.name}}</h5>
                  <p class="card-text">{{object.price}}</p>
                </div>
              </div>
            </div>
            </a>
            {% endfor %}
          </div>
    </div>
{% endblock %}